export const data = [
	{
		input: {
			PolicyID: "001",
			PolicyType: "Life",
			PremiumRange: "1000-2500",
			CoverageAmount: 5000,
			Deductible: 1000,
			EligibilityCriteria: "Adults 18-45, no pre-existing conditions",
			Benefits: "Death benefit, Education fund",
			ClaimProcess: "Online, within 15 days",
			CustomerRating: 4.5,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "LifeSecure",
			EligibilityCriteria: "Adults 18-45, no pre-existing conditions",
			Benefits: "Death benefit, Education fund",
			ClaimProcess: "Online, within 15 days",
			CustomerRating: 4.5,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "002",
			PolicyType: "Health",
			PremiumRange: "2000-3000",
			CoverageAmount: 10000,
			Deductible: 2000,
			EligibilityCriteria: "No pre-existing conditions, age 25-60",
			Benefits: "Full hospitalization, Emergency care",
			ClaimProcess: "Offline, within 30 days",
			CustomerRating: 4.7,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "HealthFirst",
			EligibilityCriteria: "No pre-existing conditions, age 25-60",
			Benefits: "Full hospitalization, Emergency care",
			ClaimProcess: "Offline, within 30 days",
			CustomerRating: 4.7,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "003",
			PolicyType: "Life",
			PremiumRange: "3000-5000",
			CoverageAmount: 15000,
			Deductible: 2500,
			EligibilityCriteria: "Adults 30-55, non-smokers",
			Benefits: "Death benefit, Accidental coverage",
			ClaimProcess: "Online, within 10 days",
			CustomerRating: 4.8,
			RenewalTerms: "15-year",
		},
		output: {
			Provider: "SecureLife",
			EligibilityCriteria: "Adults 30-55, non-smokers",
			Benefits: "Death benefit, Accidental coverage",
			ClaimProcess: "Online, within 10 days",
			CustomerRating: 4.8,
			RenewalTerms: "15-year",
		},
	},
	{
		input: {
			PolicyID: "004",
			PolicyType: "Health",
			PremiumRange: "1500-3000",
			CoverageAmount: 8000,
			Deductible: 2000,
			EligibilityCriteria: "Seniors 60+, no chronic conditions",
			Benefits: "Comprehensive hospitalization, Outpatient coverage",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.9,
			RenewalTerms: "Annual",
		},
		output: {
			Provider: "SeniorHealth",
			EligibilityCriteria: "Seniors 60+, no chronic conditions",
			Benefits: "Comprehensive hospitalization, Outpatient coverage",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.9,
			RenewalTerms: "Annual",
		},
	},
	{
		input: {
			PolicyID: "005",
			PolicyType: "Life",
			PremiumRange: "5000-7000",
			CoverageAmount: 20000,
			Deductible: 5000,
			EligibilityCriteria: "High-net-worth individuals",
			Benefits: "Estate planning, Education fund",
			ClaimProcess: "Online, within 5 days",
			CustomerRating: 4.6,
			RenewalTerms: "20-year",
		},
		output: {
			Provider: "EliteLife",
			EligibilityCriteria: "High-net-worth individuals",
			Benefits: "Estate planning, Education fund",
			ClaimProcess: "Online, within 5 days",
			CustomerRating: 4.6,
			RenewalTerms: "20-year",
		},
	},
	{
		input: {
			PolicyID: "006",
			PolicyType: "Health",
			PremiumRange: "3000-4500",
			CoverageAmount: 12000,
			Deductible: 2500,
			EligibilityCriteria: "Families with children",
			Benefits: "Pediatric care, Full hospitalization",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.3,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "FamilyCare",
			EligibilityCriteria: "Families with children",
			Benefits: "Pediatric care, Full hospitalization",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.3,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "007",
			PolicyType: "Life",
			PremiumRange: "1200-2500",
			CoverageAmount: 7000,
			Deductible: 1500,
			EligibilityCriteria: "Adults 25-50, no pre-existing conditions",
			Benefits: "Death benefit, Spousal support",
			ClaimProcess: "Online, within 20 days",
			CustomerRating: 4.4,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "TrueLife",
			EligibilityCriteria: "Adults 25-50, no pre-existing conditions",
			Benefits: "Death benefit, Spousal support",
			ClaimProcess: "Online, within 20 days",
			CustomerRating: 4.4,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "008",
			PolicyType: "Health",
			PremiumRange: "2500-4000",
			CoverageAmount: 10000,
			Deductible: 2500,
			EligibilityCriteria: "Individuals 20-60, no chronic conditions",
			Benefits: "Full hospitalization, Emergency coverage",
			ClaimProcess: "Offline, within 30 days",
			CustomerRating: 4.2,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "MedicaCare",
			EligibilityCriteria: "Individuals 20-60, no chronic conditions",
			Benefits: "Full hospitalization, Emergency coverage",
			ClaimProcess: "Offline, within 30 days",
			CustomerRating: 4.2,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "009",
			PolicyType: "Life",
			PremiumRange: "3500-5000",
			CoverageAmount: 10000,
			Deductible: 3000,
			EligibilityCriteria: "Adults 30-55, non-smokers, good health",
			Benefits: "Death benefit, Critical illness",
			ClaimProcess: "Online, within 15 days",
			CustomerRating: 4.7,
			RenewalTerms: "20-year",
		},
		output: {
			Provider: "HealthyLife",
			EligibilityCriteria: "Adults 30-55, non-smokers, good health",
			Benefits: "Death benefit, Critical illness",
			ClaimProcess: "Online, within 15 days",
			CustomerRating: 4.7,
			RenewalTerms: "20-year",
		},
	},
	{
		input: {
			PolicyID: "010",
			PolicyType: "Health",
			PremiumRange: "4000-6000",
			CoverageAmount: 15000,
			Deductible: 5000,
			EligibilityCriteria: "Adults 25-60, no pre-existing conditions",
			Benefits: "Full hospitalization, Maternity care",
			ClaimProcess: "Offline, within 25 days",
			CustomerRating: 4.5,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "MediPlus",
			EligibilityCriteria: "Adults 25-60, no pre-existing conditions",
			Benefits: "Full hospitalization, Maternity care",
			ClaimProcess: "Offline, within 25 days",
			CustomerRating: 4.5,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "011",
			PolicyType: "Life",
			PremiumRange: "1000-2500",
			CoverageAmount: 5000,
			Deductible: 1000,
			EligibilityCriteria: "Young adults 18-30, non-smokers",
			Benefits: "Basic death benefit, Education support",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.3,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "YouthLife",
			EligibilityCriteria: "Young adults 18-30, non-smokers",
			Benefits: "Basic death benefit, Education support",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.3,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "012",
			PolicyType: "Health",
			PremiumRange: "2500-4500",
			CoverageAmount: 10000,
			Deductible: 2000,
			EligibilityCriteria: "Families with no pre-existing conditions",
			Benefits: "Family coverage, Emergency room visits",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.1,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "FamilyHealth",
			EligibilityCriteria: "Families with no pre-existing conditions",
			Benefits: "Family coverage, Emergency room visits",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.1,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "013",
			PolicyType: "Life",
			PremiumRange: "3000-6000",
			CoverageAmount: 20000,
			Deductible: 5000,
			EligibilityCriteria: "Adults 40-65, no critical illnesses",
			Benefits: "Death benefit, Estate planning",
			ClaimProcess: "Online, within 10 days",
			CustomerRating: 4.7,
			RenewalTerms: "25-year",
		},
		output: {
			Provider: "SeniorLife",
			EligibilityCriteria: "Adults 40-65, no critical illnesses",
			Benefits: "Death benefit, Estate planning",
			ClaimProcess: "Online, within 10 days",
			CustomerRating: 4.7,
			RenewalTerms: "25-year",
		},
	},
	{
		input: {
			PolicyID: "014",
			PolicyType: "Health",
			PremiumRange: "2000-3000",
			CoverageAmount: 7000,
			Deductible: 2000,
			EligibilityCriteria: "Individuals 18-40, no chronic diseases",
			Benefits: "Full hospitalization, Mental health coverage",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.2,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "MindCare",
			EligibilityCriteria: "Individuals 18-40, no chronic diseases",
			Benefits: "Full hospitalization, Mental health coverage",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.2,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "015",
			PolicyType: "Life",
			PremiumRange: "4000-7000",
			CoverageAmount: 15000,
			Deductible: 3000,
			EligibilityCriteria: "Non-smokers, adults 35-60",
			Benefits: "Death benefit, Terminal illness coverage",
			ClaimProcess: "Online, within 5 days",
			CustomerRating: 4.9,
			RenewalTerms: "15-year",
		},
		output: {
			Provider: "LifeGuard",
			EligibilityCriteria: "Non-smokers, adults 35-60",
			Benefits: "Death benefit, Terminal illness coverage",
			ClaimProcess: "Online, within 5 days",
			CustomerRating: 4.9,
			RenewalTerms: "15-year",
		},
	},
	{
		input: {
			PolicyID: "016",
			PolicyType: "Health",
			PremiumRange: "1000-2500",
			CoverageAmount: 5000,
			Deductible: 1000,
			EligibilityCriteria: "Young adults, no pre-existing conditions",
			Benefits: "Basic hospitalization, Emergency care",
			ClaimProcess: "Offline, within 10 days",
			CustomerRating: 4.5,
			RenewalTerms: "3-year",
		},
		output: {
			Provider: "YouthCare",
			EligibilityCriteria: "Young adults, no pre-existing conditions",
			Benefits: "Basic hospitalization, Emergency care",
			ClaimProcess: "Offline, within 10 days",
			CustomerRating: 4.5,
			RenewalTerms: "3-year",
		},
	},
	{
		input: {
			PolicyID: "017",
			PolicyType: "Life",
			PremiumRange: "2000-4000",
			CoverageAmount: 10000,
			Deductible: 2500,
			EligibilityCriteria: "Adults 30-55, good health",
			Benefits: "Death benefit, Disability coverage",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.6,
			RenewalTerms: "20-year",
		},
		output: {
			Provider: "VitalLife",
			EligibilityCriteria: "Adults 30-55, good health",
			Benefits: "Death benefit, Disability coverage",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.6,
			RenewalTerms: "20-year",
		},
	},
	{
		input: {
			PolicyID: "018",
			PolicyType: "Health",
			PremiumRange: "2500-4500",
			CoverageAmount: 12000,
			Deductible: 2000,
			EligibilityCriteria: "Families with young children",
			Benefits: "Family hospitalization, Childcare coverage",
			ClaimProcess: "Offline, within 25 days",
			CustomerRating: 4.8,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "CareFamily",
			EligibilityCriteria: "Families with young children",
			Benefits: "Family hospitalization, Childcare coverage",
			ClaimProcess: "Offline, within 25 days",
			CustomerRating: 4.8,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "019",
			PolicyType: "Life",
			PremiumRange: "5000-8000",
			CoverageAmount: 30000,
			Deductible: 7000,
			EligibilityCriteria: "High-net-worth individuals",
			Benefits: "Wealth management, Death benefit",
			ClaimProcess: "Online, within 5 days",
			CustomerRating: 4.7,
			RenewalTerms: "25-year",
		},
		output: {
			Provider: "LuxLife",
			EligibilityCriteria: "High-net-worth individuals",
			Benefits: "Wealth management, Death benefit",
			ClaimProcess: "Online, within 5 days",
			CustomerRating: 4.7,
			RenewalTerms: "25-year",
		},
	},
	{
		input: {
			PolicyID: "020",
			PolicyType: "Health",
			PremiumRange: "3000-5000",
			CoverageAmount: 10000,
			Deductible: 3000,
			EligibilityCriteria: "Adults 18-45, no pre-existing conditions",
			Benefits: "Maternity care, Emergency room",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.3,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "PrimeHealth",
			EligibilityCriteria: "Adults 18-45, no pre-existing conditions",
			Benefits: "Maternity care, Emergency room",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.3,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "021",
			PolicyType: "Life",
			PremiumRange: "1000-3000",
			CoverageAmount: 7000,
			Deductible: 1500,
			EligibilityCriteria: "Young adults, non-smokers",
			Benefits: "Death benefit, Accidental death",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.5,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "AccuLife",
			EligibilityCriteria: "Young adults, non-smokers",
			Benefits: "Death benefit, Accidental death",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.5,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "022",
			PolicyType: "Health",
			PremiumRange: "2000-4000",
			CoverageAmount: 12000,
			Deductible: 2500,
			EligibilityCriteria: "Families, no chronic conditions",
			Benefits: "Emergency care, Family hospitalization",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.4,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "TotalCare",
			EligibilityCriteria: "Families, no chronic conditions",
			Benefits: "Emergency care, Family hospitalization",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.4,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "023",
			PolicyType: "Life",
			PremiumRange: "4000-6000",
			CoverageAmount: 20000,
			Deductible: 3000,
			EligibilityCriteria: "Adults 30-60, good health",
			Benefits: "Death benefit, Spouse support",
			ClaimProcess: "Online, within 20 days",
			CustomerRating: 4.6,
			RenewalTerms: "15-year",
		},
		output: {
			Provider: "LifeCare",
			EligibilityCriteria: "Adults 30-60, good health",
			Benefits: "Death benefit, Spouse support",
			ClaimProcess: "Online, within 20 days",
			CustomerRating: 4.6,
			RenewalTerms: "15-year",
		},
	},
	{
		input: {
			PolicyID: "024",
			PolicyType: "Health",
			PremiumRange: "3500-5000",
			CoverageAmount: 15000,
			Deductible: 3000,
			EligibilityCriteria: "Young adults, no pre-existing conditions",
			Benefits: "Hospitalization, Emergency care",
			ClaimProcess: "Offline, within 10 days",
			CustomerRating: 4.7,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "ActiveHealth",
			EligibilityCriteria: "Young adults, no pre-existing conditions",
			Benefits: "Hospitalization, Emergency care",
			ClaimProcess: "Offline, within 10 days",
			CustomerRating: 4.7,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "025",
			PolicyType: "Life",
			PremiumRange: "6000-9000",
			CoverageAmount: 30000,
			Deductible: 4000,
			EligibilityCriteria: "High-net-worth individuals",
			Benefits: "Wealth management, Death benefit",
			ClaimProcess: "Online, within 7 days",
			CustomerRating: 4.9,
			RenewalTerms: "30-year",
		},
		output: {
			Provider: "PlatinumLife",
			EligibilityCriteria: "High-net-worth individuals",
			Benefits: "Wealth management, Death benefit",
			ClaimProcess: "Online, within 7 days",
			CustomerRating: 4.9,
			RenewalTerms: "30-year",
		},
	},
	{
		input: {
			PolicyID: "026",
			PolicyType: "Health",
			PremiumRange: "2500-4000",
			CoverageAmount: 10000,
			Deductible: 1500,
			EligibilityCriteria: "Adults 18-50, no chronic diseases",
			Benefits: "Full hospitalization, Emergency care",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.6,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "MediShield",
			EligibilityCriteria: "Adults 18-50, no chronic diseases",
			Benefits: "Full hospitalization, Emergency care",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.6,
			RenewalTerms: "10-year",
		},
	},
	{
		input: {
			PolicyID: "027",
			PolicyType: "Life",
			PremiumRange: "3000-5000",
			CoverageAmount: 15000,
			Deductible: 2500,
			EligibilityCriteria: "Adults 30-60, non-smokers",
			Benefits: "Death benefit, Spouse support",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.4,
			RenewalTerms: "20-year",
		},
		output: {
			Provider: "PrimeLife",
			EligibilityCriteria: "Adults 30-60, non-smokers",
			Benefits: "Death benefit, Spouse support",
			ClaimProcess: "Online, within 30 days",
			CustomerRating: 4.4,
			RenewalTerms: "20-year",
		},
	},
	{
		input: {
			PolicyID: "028",
			PolicyType: "Health",
			PremiumRange: "1500-3000",
			CoverageAmount: 7000,
			Deductible: 2000,
			EligibilityCriteria: "Families, no pre-existing conditions",
			Benefits: "Full hospitalization, Pediatric care",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.8,
			RenewalTerms: "5-year",
		},
		output: {
			Provider: "CarePlus",
			EligibilityCriteria: "Families, no pre-existing conditions",
			Benefits: "Full hospitalization, Pediatric care",
			ClaimProcess: "Offline, within 15 days",
			CustomerRating: 4.8,
			RenewalTerms: "5-year",
		},
	},
	{
		input: {
			PolicyID: "029",
			PolicyType: "Life",
			PremiumRange: "4000-7000",
			CoverageAmount: 20000,
			Deductible: 3500,
			EligibilityCriteria: "Adults 40-65, no chronic conditions",
			Benefits: "Death benefit, Critical illness",
			ClaimProcess: "Online, within 15 days",
			CustomerRating: 4.9,
			RenewalTerms: "25-year",
		},
		output: {
			Provider: "HealthGuard",
			EligibilityCriteria: "Adults 40-65, no chronic conditions",
			Benefits: "Death benefit, Critical illness",
			ClaimProcess: "Online, within 15 days",
			CustomerRating: 4.9,
			RenewalTerms: "25-year",
		},
	},
	{
		input: {
			PolicyID: "030",
			PolicyType: "Health",
			PremiumRange: "3000-5000",
			CoverageAmount: 12000,
			Deductible: 3000,
			EligibilityCriteria: "Adults 25-55, good health",
			Benefits: "Full hospitalization, Emergency coverage",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.7,
			RenewalTerms: "10-year",
		},
		output: {
			Provider: "WellCare",
			EligibilityCriteria: "Adults 25-55, good health",
			Benefits: "Full hospitalization, Emergency coverage",
			ClaimProcess: "Offline, within 20 days",
			CustomerRating: 4.7,
			RenewalTerms: "10-year",
		},
	},
];
